### ISSUE TITLE
LD_AUDIT performance patch

### ISSUE THREAD

**Issue by hoytech** [amonakov/on-wrapping#1]
Hello and thanks for this very useful document.

I've been looking into LD_AUDIT and I believe it could be very useful, except for the performance issue you describe. Has there been any more progress on getting your patch accepted?

**Comment by amonakov** [comment]
No, after a few pings and months a review was posted requesting a change to the overall approach taken by the patch, and I felt disappointed and decided to drop the matter completely.

Note that LD_AUDIT is not a portable interface, it was invented on Solaris, and Glibc mostly followed Solaris' specs I believe. You won't find it on BSD libcs, Bionic libc (on Android), nor on Linux with musl libc. And on Linux I'm aware of only one serious consumer of LD_AUDIT (among open/free software), the latrace tool. It's not seriously exercised, has problems with debugging (code in audit modules not visible in gdb).

**Comment by hoytech** [comment]
Thank you for the information. I have downloaded latrace and am experimenting with it and I've found another issue: Binaries compiled with relro now (ie `-Wl,-z,norelro -Wl,-z,nonow`) cannot be traced, which I am assuming is another limitation with LD_AUDIT.

It's unfortunate there is no "perfect" solution to wrapping a library. I like your `LD_LIBRARY_PATH` and IFUNC solution you've used in primus, but it seems as though you need to maintain a list of every function in the wrapped library, is that correct?

Thanks!

**Comment by amonakov** [comment]
> Binaries compiled with relro now (ie -Wl,-z,norelro -Wl,-z,nonow)

(you probably meant `-Wl,-z,relro -Wl,-z,now`)

> cannot be traced, which I am assuming is another limitation with LD_AUDIT.

Yes, this is most likely because it relies on presence of PLT to hook dynamic calls, and with modern binutils PLT is omitted when bind-now is enabled (all dynamic calls are done via GOT without PLT).

> you need to maintain a list of every function in the wrapped library, is that correct?

Yes, but that's because I want to subset the wrapped interface, i.e. to omit some glXFooBarEXT functions that primus does not implement. If the wrapper aims to expose the same interface as the wrapped library, the approach taken in glxoffload (linking the wrapper against the wrapped library) is preferable I think.

**Comment by hoytech** [comment]
Sorry, yes that is what I meant: bad copy/paste.

I'll check out the glxoffload implementation, thanks!
